version: '3.7'

services:
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: